# @package _global_
training:
  task_name: Go2JoystickFlat
  sim_backend: motrix
algo:
  num_envs: 1024
  learning_starts: 10
  max_iterations: 5000
  save_interval: 1000
  updates_per_step: 8
  batch_size: 8192
  replay_buffer_n: 1024
env:
  commands:
    vel_limit:
      - [0.5, 0.0, 0.0]
      - [0.5, 0.0, 0.0]
  domain_rand:
    randomize_kp: false
    randomize_kd: false
reward:
  scales:
    tracking_lin_vel: 1.0
    tracking_ang_vel: 0.2
    lin_vel_z: -5.0
    ang_vel_xy: -0.1
    base_height: -100.0
    action_rate: -0.005
    similar_to_default: -0.1
    contact: 0.24
    swing_feet_z: 4.0
  tracking_sigma: 0.25
  base_height_target: 0.3
